# Instructions
EXIT_INSTRUCTION = "EXIT"
RUN_INSTRUCTION = "RUN ITERATION"


# Message Headers
OWN_FEATURES = "OWN FEATURES"
OTHER_FEATURES = "OTHER FEATURES"
PARAMS = "PARAMS"
THETAS = "THETAS"
RESULTS = "RESULTS"