# initial_thetas: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
epochs: 10
log_level: "DEBUG"
random_seed: 42
q_depth: 4
n_shots: 1
n_samples: 10 # only used for the MOONS dataset, in the IRIS this defaults to 150
test_size: 0.2
# either MOONS or IRIS
dataset_function: "MOONS"
start_from_checkpoint: False
n_qubits: 2
#layers_with_rcnot: [0,1,2,3]

