# initial_thetas: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
num_iter: 100
enable_netqasm_logging: False
batch_size: 16
learning_rate: 0.01
random_seed: 42
q_depth: 4
n_shots: 2
n_samples: 100
test_size: 0.2
# either MOONS or IRIS
dataset_function: "MOONS"