# Default Config File, for all parameters see: utils/config_parser.py
epochs: 10
log_level: "DEBUG"
enable_netqasm_logs: False
random_seed: 42
q_depth: 4
n_shots: 1
n_samples: 10 # only used for the MOONS dataset, in the IRIS this defaults to 100
test_size: 0.2
dataset_function: "MOONS" # either MOONS or IRIS
start_from_checkpoint: False
n_qubits: 2
use_default_network_config: False
use_expectation_values: False
link_fidelity: 1
layers_with_rcnot: [0,1,2,3]
lb_inputs: 0
ub_inputs: 1
lb_params: None # None means using default
ub_params: None # None means using default
netqasm_simulator: "netsquid_single_thread"

